sudo: true

language: node_js

node_js:
  - node

branches:
  only:
    - main

cache:
  directories:
    - /client/node_modules

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: main
