sudo: true

language: node_js

node_js:
  - node

branches:
  only:
    - main

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: main
